
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hayat4144/node-server:latest

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push hayat4144/node-server:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #
  #   steps:
  #   # Step 5: Deploy to the server
  #   - name: Deploy to server
  #     run: |
  #       ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
  #       docker pull your-dockerhub-username/exress-server:latest
  #       docker stop exress-server || true
  #       docker rm exress-server || true
  #       docker run -d --name exress-server -p 80:4000 your-dockerhub-username/exress-server:latest
  #       EOF

